---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: receiver
  minReplicaCount: 1
  triggers:
  - type: rabbitmq
    metadata:
      host: "http://guest:guest@rabbitmq1:15672/"
      queueName: 'ticket-queue'
      mode: QueueLength
      value: '5'
      vhostName: /
